version: "3.3"

volumes:
  next_static_files:

services:
  prod:
    build: .
    ports: 
      - '8000:8000'
    volumes: 
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=personal_website.settings.prod
    env_file: .django.prod.env
    depends_on:
      - prod_db
    command:
      bash -c "/wait-for-postgres.sh prod_db -- 'python manage.py migrate' && python manage.py collectstatic --noinput && gunicorn personal_website.wsgi:application -w 2 -b :8000"
    restart: 
      always

  nginx:
    build: ./nginx 
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./staticfiles:/staticfiles
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/archive/andrewcullen.ie:/etc/nginx/ssl/andrewcullen.ie
      - next_static_files:/usr/share/nginx/html/_next
    depends_on:
      - prod_frontend
      - prod
    restart: 
      always

  prod_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - next_static_files:/app/.next
    env_file:
      - .next.prod.env
    restart: 
      always

  prod_db:
    build:
      context: ./db
    env_file: .django.prod.env
    restart: 
      always
