version: "3.3"
services:
  prod:
    build: .
    ports: 
      - '8000:8000'
    volumes: 
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=personal_website.settings.prod
    env_file: .django.prod.env
    depends_on:
      - prod_db
    command:
      bash -c "/wait-for-postgres.sh prod_db -- 'python manage.py migrate' && python manage.py collectstatic --noinput && gunicorn personal_website.wsgi:application -w 2 -b :8000"
    restart: 
      always

  nginx:
    image: nginx:1.19.0-alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/staticfiles
    depends_on:
      - prod_frontend
    restart: 
      always

  prod_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
    depends_on:
      - prod
    env_file:
      - .next.prod.env
    restart: 
      always

  prod_db:
    build:
      context: ./db
    env_file: .django.prod.env
    restart: 
      always
